import { LevelData } from '../types';

export const GAME_LEVELS: LevelData[] = [
  {
    id: 1,
    title: 'Isole del Risveglio',
    subtitle: 'The Awakening Isles',
    description: 'Raccogli le 3 rune magiche, usa il rampino per superare il baratro e attiva il primo portale celeste.',
    playerSpawn: [0, 2.5, 0],
    fioccoSpawn: [2.5, 0.6, 2.0],
    portalPosition: [0, 4.5, -45],
    requiredRunes: 3,
    skyColorTop: '#4a90e2',
    skyColorBottom: '#fce4a6',
    fogColor: '#bde0fe',
    sunColor: '#fff3b0',
    islands: [
      // Starting island
      {
        id: 'start_island',
        position: [0, 0, 0],
        radius: 12,
        height: 10,
        shape: 'irregular',
        theme: 'grass',
        treesCount: 6,
        pillarsCount: 2,
      },
      // Intermediate stepping island
      {
        id: 'middle_island',
        position: [18, 1.5, -20],
        radius: 9,
        height: 8,
        shape: 'circle',
        theme: 'ruins',
        treesCount: 3,
        pillarsCount: 4,
        hasWaterfall: true,
      },
      // Guardian & rune island
      {
        id: 'guardian_island',
        position: [-16, 2, -22],
        radius: 10,
        height: 9,
        shape: 'oval',
        theme: 'ruins',
        treesCount: 4,
        pillarsCount: 3,
      },
      // Goal Portal sanctuary
      {
        id: 'portal_island',
        position: [0, 3.5, -45],
        radius: 11,
        height: 12,
        shape: 'plateau',
        theme: 'temple',
        treesCount: 2,
        pillarsCount: 6,
      },
    ],
    grappleAnchors: [
      // Anchor over chasm to middle island
      {
        id: 'anchor_1',
        position: [9, 8, -10],
        type: 'crystal',
      },
      // Anchor over chasm to guardian island
      {
        id: 'anchor_2',
        position: [-8, 7.5, -11],
        type: 'crystal',
      },
      // Anchor linking to portal sanctuary
      {
        id: 'anchor_3',
        position: [0, 9.5, -32],
        type: 'floating_relic',
      },
    ],
    runes: [
      // Rune 1 on start island edge behind ancient pillar
      {
        id: 'rune_1_1',
        position: [6, 2, 5],
        color: '#38ef7d',
      },
      // Rune 2 on middle island
      {
        id: 'rune_1_2',
        position: [20, 3.5, -20],
        color: '#38ef7d',
      },
      // Rune 3 guarded on guardian island
      {
        id: 'rune_1_3',
        position: [-18, 4, -25],
        color: '#38ef7d',
      },
    ],
    guardians: [
      {
        id: 'guardian_1_1',
        spawnPosition: [-14, 2.8, -20],
        patrolPoints: [
          [-14, 2.8, -20],
          [-19, 2.8, -24],
          [-12, 2.8, -25],
        ],
        detectionRadius: 10,
        speed: 3.2,
        scale: 1.1,
        type: 'standard',
      },
    ],
    bouncePads: [
      {
        id: 'pad_1_1',
        position: [18, 1.8, -20],
        power: 16,
      },
    ],
  },
  {
    id: 2,
    title: 'Rovine Celesti',
    subtitle: 'Ancient Sky Ruins',
    description: 'Baratri più ampi e 2 Guardiani di Pietra. Usa catene di rampini a mezzaria per raggiungere le rune!',
    playerSpawn: [0, 2.5, 0],
    fioccoSpawn: [2.5, 0.6, 2.0],
    portalPosition: [28, 7.5, -55],
    requiredRunes: 4,
    skyColorTop: '#3a7bd5',
    skyColorBottom: '#f9d423',
    fogColor: '#ffd166',
    sunColor: '#ffeaa7',
    islands: [
      // Start island
      {
        id: 'start_island_2',
        position: [0, 0, 0],
        radius: 11,
        height: 10,
        shape: 'circle',
        theme: 'grass',
        treesCount: 5,
        pillarsCount: 2,
      },
      // Floating High Arch Island
      {
        id: 'arch_island',
        position: [-22, 3, -15],
        radius: 10,
        height: 10,
        shape: 'irregular',
        theme: 'ruins',
        treesCount: 3,
        pillarsCount: 5,
        hasWaterfall: true,
      },
      // Central sunken ruin island
      {
        id: 'central_ruin',
        position: [2, 1, -30],
        radius: 14,
        height: 11,
        shape: 'plateau',
        theme: 'ruins',
        treesCount: 4,
        pillarsCount: 6,
      },
      // East cliff
      {
        id: 'east_cliff',
        position: [25, 4, -22],
        radius: 8,
        height: 9,
        shape: 'oval',
        theme: 'grass',
        treesCount: 3,
        pillarsCount: 2,
      },
      // Final Sky Temple
      {
        id: 'temple_peak_2',
        position: [28, 6.5, -55],
        radius: 12,
        height: 14,
        shape: 'plateau',
        theme: 'temple',
        treesCount: 2,
        pillarsCount: 8,
        hasWaterfall: true,
      },
    ],
    grappleAnchors: [
      // Chasm to Arch island
      {
        id: 'anchor_2_1',
        position: [-11, 7.5, -8],
        type: 'crystal',
      },
      // Chasm to Central ruin
      {
        id: 'anchor_2_2',
        position: [1, 7, -15],
        type: 'crystal',
      },
      // Mid-air floating anchor over giant void
      {
        id: 'anchor_2_3',
        position: [-12, 10, -32],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [4, 0, 0],
        moveSpeed: 1.2,
      },
      // Chasm from central to East cliff
      {
        id: 'anchor_2_4',
        position: [14, 8, -25],
        type: 'crystal',
      },
      // High anchor to final temple
      {
        id: 'anchor_2_5',
        position: [16, 12, -44],
        type: 'floating_relic',
      },
    ],
    runes: [
      {
        id: 'rune_2_1',
        position: [-24, 5, -17],
        color: '#00f2fe',
      },
      {
        id: 'rune_2_2',
        position: [26, 6, -23],
        color: '#00f2fe',
      },
      {
        id: 'rune_2_3',
        position: [4, 3, -33],
        color: '#00f2fe',
      },
      {
        id: 'rune_2_4',
        position: [-1, 3.5, -24],
        color: '#00f2fe',
      },
    ],
    guardians: [
      {
        id: 'guardian_2_1',
        spawnPosition: [2, 2.5, -30],
        patrolPoints: [
          [2, 2.5, -30],
          [7, 2.5, -33],
          [-3, 2.5, -32],
          [2, 2.5, -26],
        ],
        detectionRadius: 11,
        speed: 3.5,
        scale: 1.2,
        type: 'standard',
      },
      {
        id: 'guardian_2_2',
        spawnPosition: [-21, 4.5, -15],
        patrolPoints: [
          [-21, 4.5, -15],
          [-25, 4.5, -18],
          [-19, 4.5, -12],
        ],
        detectionRadius: 10,
        speed: 3.3,
        scale: 1.0,
        type: 'swift',
      },
    ],
    windUpdrafts: [
      {
        id: 'wind_2_1',
        position: [2, 1.2, -30],
        height: 18,
        radius: 4,
      },
    ],
  },
  {
    id: 3,
    title: 'Il Picco dei Guardiani',
    subtitle: 'The Guardian Peak',
    description: 'Il santuario supremo tra le vette celesti. 5 rune, 3 Guardiani di Pietra e ancore semoventi per la sfida finale!',
    playerSpawn: [0, 2.5, 0],
    fioccoSpawn: [2.5, 0.6, 2.0],
    portalPosition: [0, 11, -72],
    requiredRunes: 5,
    skyColorTop: '#2b5876',
    skyColorBottom: '#ff8a00',
    fogColor: '#e0c3fc',
    sunColor: '#ffecd2',
    islands: [
      // Start island
      {
        id: 'start_island_3',
        position: [0, 0, 0],
        radius: 12,
        height: 11,
        shape: 'circle',
        theme: 'grass',
        treesCount: 6,
        pillarsCount: 3,
      },
      // Left Floating Island
      {
        id: 'left_island_3',
        position: [-26, 2, -18],
        radius: 10,
        height: 9,
        shape: 'irregular',
        theme: 'ruins',
        treesCount: 3,
        pillarsCount: 4,
        hasWaterfall: true,
      },
      // Right Floating Island
      {
        id: 'right_island_3',
        position: [26, 3, -18],
        radius: 10,
        height: 9,
        shape: 'irregular',
        theme: 'ruins',
        treesCount: 3,
        pillarsCount: 4,
        hasWaterfall: true,
      },
      // Colossus Arena Island
      {
        id: 'arena_island_3',
        position: [0, 4, -38],
        radius: 16,
        height: 12,
        shape: 'plateau',
        theme: 'temple',
        treesCount: 4,
        pillarsCount: 8,
      },
      // Tower Islet Left
      {
        id: 'tower_left',
        position: [-22, 7, -54],
        radius: 8,
        height: 10,
        shape: 'circle',
        theme: 'ruins',
        treesCount: 2,
        pillarsCount: 3,
      },
      // Tower Islet Right
      {
        id: 'tower_right',
        position: [22, 7, -54],
        radius: 8,
        height: 10,
        shape: 'circle',
        theme: 'ruins',
        treesCount: 2,
        pillarsCount: 3,
      },
      // Master Sanctuary
      {
        id: 'sanctuary_peak',
        position: [0, 10, -72],
        radius: 14,
        height: 15,
        shape: 'plateau',
        theme: 'temple',
        treesCount: 3,
        pillarsCount: 10,
        hasWaterfall: true,
      },
    ],
    grappleAnchors: [
      // Start to left
      {
        id: 'anchor_3_1',
        position: [-13, 8, -9],
        type: 'crystal',
      },
      // Start to right
      {
        id: 'anchor_3_2',
        position: [13, 8, -9],
        type: 'crystal',
      },
      // Left to Arena
      {
        id: 'anchor_3_3',
        position: [-13, 9, -28],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [0, 2, 0],
        moveSpeed: 1.5,
      },
      // Right to Arena
      {
        id: 'anchor_3_4',
        position: [13, 9, -28],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [0, 2, 0],
        moveSpeed: 1.5,
      },
      // Arena to Tower Left
      {
        id: 'anchor_3_5',
        position: [-12, 12, -46],
        type: 'crystal',
      },
      // Arena to Tower Right
      {
        id: 'anchor_3_6',
        position: [12, 12, -46],
        type: 'crystal',
      },
      // Towers to Master Sanctuary
      {
        id: 'anchor_3_7',
        position: [0, 15, -63],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [5, 0, 0],
        moveSpeed: 1.8,
      },
    ],
    runes: [
      {
        id: 'rune_3_1',
        position: [-28, 4.5, -20],
        color: '#ff007f',
      },
      {
        id: 'rune_3_2',
        position: [28, 5.5, -20],
        color: '#ff007f',
      },
      {
        id: 'rune_3_3',
        position: [-22, 9.5, -55],
        color: '#ff007f',
      },
      {
        id: 'rune_3_4',
        position: [22, 9.5, -55],
        color: '#ff007f',
      },
      {
        id: 'rune_3_5',
        position: [0, 5.6, -26],
        color: '#ff007f',
      },
    ],
    guardians: [
      // Arena Colossus
      {
        id: 'guardian_3_colossus',
        spawnPosition: [0, 5.5, -38],
        patrolPoints: [
          [0, 5.5, -38],
          [6, 5.5, -34],
          [-6, 5.5, -34],
          [0, 5.5, -42],
        ],
        detectionRadius: 13,
        speed: 3.6,
        scale: 1.4,
        type: 'colossus',
      },
      // Left Tower Sentinel
      {
        id: 'guardian_3_left',
        spawnPosition: [-25, 4.5, -17],
        patrolPoints: [
          [-25, 4.5, -17],
          [-27, 4.5, -21],
        ],
        detectionRadius: 9,
        speed: 3.4,
        scale: 1.0,
        type: 'standard',
      },
      // Right Tower Sentinel
      {
        id: 'guardian_3_right',
        spawnPosition: [25, 5.5, -17],
        patrolPoints: [
          [25, 5.5, -17],
          [27, 5.5, -21],
        ],
        detectionRadius: 9,
        speed: 3.4,
        scale: 1.0,
        type: 'standard',
      },
    ],
    bouncePads: [
      {
        id: 'pad_3_left',
        position: [-26, 2.4, -18],
        power: 18,
      },
      {
        id: 'pad_3_right',
        position: [26, 3.4, -18],
        power: 18,
      },
    ],
    windUpdrafts: [
      {
        id: 'wind_3_arena',
        position: [0, 4.2, -38],
        height: 20,
        radius: 5,
      },
    ],
  },
  {
    id: 4,
    title: 'Santuario dello Zenit',
    subtitle: 'Sanctuary of the Zenith',
    description: 'Vette sospese tra aurore boreali dorate. 5 rune custodite da sentinelle rapide e ancore oscillanti.',
    playerSpawn: [0, 2.5, 0],
    fioccoSpawn: [2.5, 0.6, 2.0],
    portalPosition: [0, 13.5, -80],
    requiredRunes: 5,
    skyColorTop: '#1e1b4b',
    skyColorBottom: '#f59e0b',
    fogColor: '#6366f1',
    sunColor: '#fef08a',
    islands: [
      {
        id: 'island_4_start',
        position: [0, 0, 0],
        radius: 12,
        height: 10,
        shape: 'circle',
        theme: 'temple',
        treesCount: 4,
        pillarsCount: 4,
      },
      {
        id: 'island_4_aurora_left',
        position: [-22, 4, -26],
        radius: 9,
        height: 12,
        shape: 'plateau',
        theme: 'peak',
        treesCount: 2,
        pillarsCount: 5,
      },
      {
        id: 'island_4_aurora_right',
        position: [22, 4, -26],
        radius: 9,
        height: 12,
        shape: 'plateau',
        theme: 'peak',
        treesCount: 2,
        pillarsCount: 5,
      },
      {
        id: 'island_4_mid_sanctuary',
        position: [0, 7.5, -52],
        radius: 14,
        height: 14,
        shape: 'irregular',
        theme: 'ruins',
        treesCount: 5,
        pillarsCount: 8,
        hasWaterfall: true,
      },
      {
        id: 'island_4_apex',
        position: [0, 12, -80],
        radius: 11,
        height: 16,
        shape: 'plateau',
        theme: 'temple',
        treesCount: 3,
        pillarsCount: 6,
      },
    ],
    grappleAnchors: [
      {
        id: 'anchor_4_1',
        position: [-11, 8.5, -13],
        type: 'crystal',
      },
      {
        id: 'anchor_4_2',
        position: [11, 8.5, -13],
        type: 'crystal',
      },
      {
        id: 'anchor_4_3',
        position: [-12, 11, -39],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [0, 3, 0],
        moveSpeed: 2.0,
      },
      {
        id: 'anchor_4_4',
        position: [12, 11, -39],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [0, 3, 0],
        moveSpeed: 2.0,
      },
      {
        id: 'anchor_4_5',
        position: [0, 14, -66],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [6, 0, 0],
        moveSpeed: 2.2,
      },
    ],
    runes: [
      {
        id: 'rune_4_1',
        position: [-22, 6.2, -26],
        color: '#fbbf24',
      },
      {
        id: 'rune_4_2',
        position: [22, 6.2, -26],
        color: '#fbbf24',
      },
      {
        id: 'rune_4_3',
        position: [-7, 9.8, -52],
        color: '#fbbf24',
      },
      {
        id: 'rune_4_4',
        position: [7, 9.8, -52],
        color: '#fbbf24',
      },
      {
        id: 'rune_4_5',
        position: [0, 9.8, -57],
        color: '#fbbf24',
      },
    ],
    guardians: [
      {
        id: 'guardian_4_1',
        spawnPosition: [-20, 6, -26],
        patrolPoints: [
          [-20, 6, -26],
          [-24, 6, -26],
        ],
        detectionRadius: 9,
        speed: 3.8,
        scale: 1.0,
        type: 'swift',
      },
      {
        id: 'guardian_4_2',
        spawnPosition: [20, 6, -26],
        patrolPoints: [
          [20, 6, -26],
          [24, 6, -26],
        ],
        detectionRadius: 9,
        speed: 3.8,
        scale: 1.0,
        type: 'swift',
      },
      {
        id: 'guardian_4_colossus',
        spawnPosition: [0, 9.5, -52],
        patrolPoints: [
          [0, 9.5, -52],
          [5, 9.5, -48],
          [-5, 9.5, -48],
        ],
        detectionRadius: 14,
        speed: 3.5,
        scale: 1.4,
        type: 'colossus',
      },
    ],
    bouncePads: [
      {
        id: 'pad_4_start',
        position: [0, 0.4, -6],
        power: 17,
      },
      {
        id: 'pad_4_left',
        position: [-22, 4.4, -26],
        power: 18,
      },
      {
        id: 'pad_4_right',
        position: [22, 4.4, -26],
        power: 18,
      },
    ],
    windUpdrafts: [
      {
        id: 'wind_4_mid',
        position: [0, 8.0, -52],
        height: 20,
        radius: 5,
      },
    ],
  },
  {
    id: 5,
    title: 'Nucleo Celeste Eterno',
    subtitle: 'The Eternal Core',
    description: 'La sfida finale nel cuore delle stelle. 6 rune radiose, guardiani colossali e l\'attivazione della Stella Madre.',
    playerSpawn: [0, 2.5, 0],
    fioccoSpawn: [2.5, 0.6, 2.0],
    portalPosition: [0, 16.5, -95],
    requiredRunes: 6,
    skyColorTop: '#0f172a',
    skyColorBottom: '#ec4899',
    fogColor: '#8b5cf6',
    sunColor: '#f472b6',
    islands: [
      {
        id: 'island_5_start',
        position: [0, 0, 0],
        radius: 12,
        height: 10,
        shape: 'plateau',
        theme: 'temple',
        treesCount: 3,
        pillarsCount: 6,
      },
      {
        id: 'island_5_star_left',
        position: [-26, 5, -30],
        radius: 10,
        height: 14,
        shape: 'oval',
        theme: 'peak',
        treesCount: 2,
        pillarsCount: 6,
      },
      {
        id: 'island_5_star_right',
        position: [26, 5, -30],
        radius: 10,
        height: 14,
        shape: 'oval',
        theme: 'peak',
        treesCount: 2,
        pillarsCount: 6,
      },
      {
        id: 'island_5_grand_citadel',
        position: [0, 9.5, -60],
        radius: 16,
        height: 16,
        shape: 'plateau',
        theme: 'temple',
        treesCount: 6,
        pillarsCount: 10,
        hasWaterfall: true,
      },
      {
        id: 'island_5_mother_star',
        position: [0, 15, -95],
        radius: 13,
        height: 18,
        shape: 'circle',
        theme: 'temple',
        treesCount: 4,
        pillarsCount: 8,
      },
    ],
    grappleAnchors: [
      {
        id: 'anchor_5_1',
        position: [-13, 9, -15],
        type: 'crystal',
      },
      {
        id: 'anchor_5_2',
        position: [13, 9, -15],
        type: 'crystal',
      },
      {
        id: 'anchor_5_3',
        position: [-14, 12, -45],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [0, 3, 0],
        moveSpeed: 2.2,
      },
      {
        id: 'anchor_5_4',
        position: [14, 12, -45],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [0, 3, 0],
        moveSpeed: 2.2,
      },
      {
        id: 'anchor_5_5',
        position: [0, 17, -78],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [7, 2, 0],
        moveSpeed: 2.4,
      },
    ],
    runes: [
      {
        id: 'rune_5_1',
        position: [-26, 7.2, -30],
        color: '#38bdf8',
      },
      {
        id: 'rune_5_2',
        position: [26, 7.2, -30],
        color: '#38bdf8',
      },
      {
        id: 'rune_5_3',
        position: [-8, 11.8, -60],
        color: '#38bdf8',
      },
      {
        id: 'rune_5_4',
        position: [8, 11.8, -60],
        color: '#38bdf8',
      },
      {
        id: 'rune_5_5',
        position: [0, 11.8, -68],
        color: '#38bdf8',
      },
      {
        id: 'rune_5_6',
        position: [0, 12.8, -52],
        color: '#38bdf8',
      },
    ],
    guardians: [
      {
        id: 'guardian_5_left',
        spawnPosition: [-24, 7, -30],
        patrolPoints: [
          [-24, 7, -30],
          [-28, 7, -30],
        ],
        detectionRadius: 10,
        speed: 4.0,
        scale: 1.1,
        type: 'swift',
      },
      {
        id: 'guardian_5_right',
        spawnPosition: [24, 7, -30],
        patrolPoints: [
          [24, 7, -30],
          [28, 7, -30],
        ],
        detectionRadius: 10,
        speed: 4.0,
        scale: 1.1,
        type: 'swift',
      },
      {
        id: 'guardian_5_overlord',
        spawnPosition: [0, 11.5, -60],
        patrolPoints: [
          [0, 11.5, -60],
          [6, 11.5, -55],
          [-6, 11.5, -55],
          [0, 11.5, -65],
        ],
        detectionRadius: 15,
        speed: 3.8,
        scale: 1.6,
        type: 'colossus',
      },
    ],
    bouncePads: [
      {
        id: 'pad_5_1',
        position: [-26, 6.5, -30],
        power: 18,
      },
      {
        id: 'pad_5_2',
        position: [26, 6.5, -30],
        power: 18,
      },
    ],
    windUpdrafts: [
      {
        id: 'wind_5_1',
        position: [0, 11, -60],
        height: 22,
        radius: 5,
      },
    ],
  },
  {
    id: 6,
    title: "Il Santuario dell'Eclissi",
    subtitle: 'The Eclipse Sanctuary',
    description: 'Sotto il cielo di crepuscolo cosmico, usa le correnti ascensionali e i trampolini per scalare il tempio sospeso tra le eclissi.',
    playerSpawn: [0, 2.5, 0],
    fioccoSpawn: [2.5, 0.6, 2.0],
    portalPosition: [0, 18.5, -85],
    requiredRunes: 5,
    skyColorTop: '#1e1b4b',
    skyColorBottom: '#701a75',
    fogColor: '#2e1065',
    sunColor: '#f43f5e',
    islands: [
      {
        id: 'island_6_start',
        position: [0, 0, 0],
        radius: 12,
        height: 10,
        shape: 'circle',
        theme: 'temple',
        treesCount: 4,
        pillarsCount: 4,
      },
      {
        id: 'island_6_left_tier',
        position: [-22, 5, -25],
        radius: 10,
        height: 12,
        shape: 'plateau',
        theme: 'ruins',
        treesCount: 3,
        pillarsCount: 5,
      },
      {
        id: 'island_6_right_tier',
        position: [22, 5, -25],
        radius: 10,
        height: 12,
        shape: 'plateau',
        theme: 'ruins',
        treesCount: 3,
        pillarsCount: 5,
      },
      {
        id: 'island_6_center_spire',
        position: [0, 10, -55],
        radius: 14,
        height: 16,
        shape: 'irregular',
        theme: 'temple',
        treesCount: 2,
        pillarsCount: 8,
        hasWaterfall: true,
      },
      {
        id: 'island_6_zenith_apex',
        position: [0, 17, -85],
        radius: 11,
        height: 18,
        shape: 'plateau',
        theme: 'peak',
        treesCount: 1,
        pillarsCount: 6,
      },
    ],
    grappleAnchors: [
      {
        id: 'anchor_6_1',
        position: [-10, 10, -12],
        type: 'crystal',
      },
      {
        id: 'anchor_6_2',
        position: [10, 10, -12],
        type: 'crystal',
      },
      {
        id: 'anchor_6_3',
        position: [-12, 14, -40],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [3, 2, 0],
        moveSpeed: 2.0,
      },
      {
        id: 'anchor_6_4',
        position: [12, 14, -40],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [-3, 2, 0],
        moveSpeed: 2.0,
      },
      {
        id: 'anchor_6_apex',
        position: [0, 23, -70],
        type: 'pillar_top',
      },
    ],
    runes: [
      {
        id: 'rune_6_1',
        position: [-22, 6.8, -25],
        color: '#f43f5e',
      },
      {
        id: 'rune_6_2',
        position: [22, 6.8, -25],
        color: '#f43f5e',
      },
      {
        id: 'rune_6_3',
        position: [-10, 11.5, -48],
        color: '#f43f5e',
      },
      {
        id: 'rune_6_4',
        position: [10, 11.5, -48],
        color: '#f43f5e',
      },
      {
        id: 'rune_6_5',
        position: [0, 18.2, -78],
        color: '#f43f5e',
      },
    ],
    guardians: [
      {
        id: 'guardian_6_left',
        spawnPosition: [-22, 5.5, -25],
        patrolPoints: [
          [-22, 5.5, -25],
          [-24, 5.5, -28],
        ],
        detectionRadius: 11,
        speed: 4.2,
        scale: 1.15,
        type: 'swift',
      },
      {
        id: 'guardian_6_right',
        spawnPosition: [22, 5.5, -25],
        patrolPoints: [
          [22, 5.5, -25],
          [24, 5.5, -28],
        ],
        detectionRadius: 11,
        speed: 4.2,
        scale: 1.15,
        type: 'swift',
      },
      {
        id: 'guardian_6_apex',
        spawnPosition: [0, 10.5, -55],
        patrolPoints: [
          [0, 10.5, -55],
          [5, 10.5, -52],
          [-5, 10.5, -52],
        ],
        detectionRadius: 16,
        speed: 3.9,
        scale: 1.7,
        type: 'colossus',
      },
    ],
    bouncePads: [
      {
        id: 'pad_6_start',
        position: [0, 0.4, -6],
        power: 19,
        color: 0xf43f5e,
      },
      {
        id: 'pad_6_mid_left',
        position: [-22, 5.4, -28],
        power: 20,
        color: 0xf43f5e,
      },
      {
        id: 'pad_6_mid_right',
        position: [22, 5.4, -28],
        power: 20,
        color: 0xf43f5e,
      },
    ],
    windUpdrafts: [
      {
        id: 'wind_6_center',
        position: [0, 10.2, -55],
        height: 25,
        radius: 6,
      },
    ],
  },
  {
    id: 7,
    title: "L'Acrocoro delle Stelle Infinite",
    subtitle: 'Highland of Infinite Stars',
    description: 'La prova definitiva dei Cieli: plana con le tue ali spettrali tra le vette astrali e conquista il Gran Portale della Genesi.',
    playerSpawn: [0, 2.5, 0],
    fioccoSpawn: [2.5, 0.6, 2.0],
    portalPosition: [0, 24.5, -110],
    requiredRunes: 6,
    skyColorTop: '#030712',
    skyColorBottom: '#38bdf8',
    fogColor: '#0f172a',
    sunColor: '#67e8f9',
    islands: [
      {
        id: 'island_7_nexus',
        position: [0, 0, 0],
        radius: 14,
        height: 12,
        shape: 'irregular',
        theme: 'temple',
        treesCount: 5,
        pillarsCount: 6,
      },
      {
        id: 'island_7_wing_left',
        position: [-30, 6, -32],
        radius: 11,
        height: 14,
        shape: 'plateau',
        theme: 'ruins',
        treesCount: 2,
        pillarsCount: 4,
      },
      {
        id: 'island_7_wing_right',
        position: [30, 6, -32],
        radius: 11,
        height: 14,
        shape: 'plateau',
        theme: 'ruins',
        treesCount: 2,
        pillarsCount: 4,
      },
      {
        id: 'island_7_zenith_bastion',
        position: [0, 13, -70],
        radius: 16,
        height: 18,
        shape: 'irregular',
        theme: 'temple',
        treesCount: 3,
        pillarsCount: 8,
        hasWaterfall: true,
      },
      {
        id: 'island_7_cosmic_sanctuary',
        position: [0, 23, -110],
        radius: 13,
        height: 22,
        shape: 'plateau',
        theme: 'peak',
        treesCount: 2,
        pillarsCount: 8,
      },
    ],
    grappleAnchors: [
      {
        id: 'anchor_7_1',
        position: [-16, 12, -15],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [2, 3, 0],
        moveSpeed: 2.2,
      },
      {
        id: 'anchor_7_2',
        position: [16, 12, -15],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [-2, 3, 0],
        moveSpeed: 2.2,
      },
      {
        id: 'anchor_7_3',
        position: [-20, 16, -52],
        type: 'crystal',
      },
      {
        id: 'anchor_7_4',
        position: [20, 16, -52],
        type: 'crystal',
      },
      {
        id: 'anchor_7_5',
        position: [0, 21, -90],
        type: 'floating_relic',
        isMoving: true,
        moveRange: [6, 2, 0],
        moveSpeed: 2.5,
      },
    ],
    runes: [
      {
        id: 'rune_7_1',
        position: [-30, 7.8, -32],
        color: '#38bdf8',
      },
      {
        id: 'rune_7_2',
        position: [30, 7.8, -32],
        color: '#38bdf8',
      },
      {
        id: 'rune_7_3',
        position: [-7, 14.8, -70],
        color: '#38bdf8',
      },
      {
        id: 'rune_7_4',
        position: [7, 14.8, -70],
        color: '#38bdf8',
      },
      {
        id: 'rune_7_5',
        position: [0, 16.5, -62],
        color: '#38bdf8',
      },
      {
        id: 'rune_7_6',
        position: [0, 16.5, -78],
        color: '#38bdf8',
      },
    ],
    guardians: [
      {
        id: 'guardian_7_alpha',
        spawnPosition: [-30, 6.5, -32],
        patrolPoints: [
          [-30, 6.5, -32],
          [-33, 6.5, -35],
        ],
        detectionRadius: 12,
        speed: 4.4,
        scale: 1.2,
        type: 'swift',
      },
      {
        id: 'guardian_7_beta',
        spawnPosition: [30, 6.5, -32],
        patrolPoints: [
          [30, 6.5, -32],
          [33, 6.5, -35],
        ],
        detectionRadius: 12,
        speed: 4.4,
        scale: 1.2,
        type: 'swift',
      },
      {
        id: 'guardian_7_titan',
        spawnPosition: [0, 13.5, -70],
        patrolPoints: [
          [0, 13.5, -70],
          [7, 13.5, -65],
          [-7, 13.5, -65],
          [0, 13.5, -75],
        ],
        detectionRadius: 18,
        speed: 4.1,
        scale: 1.8,
        type: 'colossus',
      },
    ],
    bouncePads: [
      {
        id: 'pad_7_start',
        position: [0, 0.4, -6],
        power: 21,
        color: 0x38bdf8,
      },
      {
        id: 'pad_7_wing_l',
        position: [-30, 6.4, -36],
        power: 22,
        color: 0x38bdf8,
      },
      {
        id: 'pad_7_wing_r',
        position: [30, 6.4, -36],
        power: 22,
        color: 0x38bdf8,
      },
    ],
    windUpdrafts: [
      {
        id: 'wind_7_mid',
        position: [0, 13.5, -70],
        height: 28,
        radius: 7,
      },
    ],
  },
];
